apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp
  labels:
    app: sample-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
        - name: sample-webapp
          image: sample-webapp:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
